name: HEXO_Deploy

on:
  push:
    branches:
      - develop

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.HEXODEPLOY }}
          submodules: recursive
          
      - name: Use Node.js 16.x
        uses: actions/setup-node@v4
        with:
          node-version: '16.x' # 更新到 Node.js 16.x 以上版本
          cache: 'npm' # 啟用內建的 npm 快取

      - name: Cache NPM dependencies
        uses: actions/cache@v3 # 更新到 v3
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.HEXODEPLOY }}
          publish_branch: main
          publish_dir: ./public
